# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'idk.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie
import sys
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.uic import loadUiType

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1269, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-80, -40, 1351, 751))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/wp2757874.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.pui= QLabel
        self.pui.movie = QtGui.QMovie("./UI/wp2757874.gif")
        self.label.setMovie(self.pui.movie)
        self.pui.movie.start()
            


        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 10, 1051, 191))
        font = QtGui.QFont()
        font.setFamily("Cinzel Black")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(500, 220, 341, 291))
        self.label_3.setStyleSheet("")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/123.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")

        self.pui= QLabel
        self.pui.movie = QtGui.QMovie("./UI/123.gif")
        self.label_3.setMovie(self.pui.movie)
        self.pui.movie.start()


        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(950, 410, 341, 251))
        self.label_5.setStyleSheet("")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/newPrefix/ascd.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")

        self.pui= QLabel
        self.pui.movie = QtGui.QMovie("./UI/ascd.gif")
        self.label_5.setMovie(self.pui.movie)
        self.pui.movie.start()


        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 630, 1261, 71))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/newPrefix/audio.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")

        self.pui= QLabel
        self.pui.movie = QtGui.QMovie("./UI/audio.gif")
        self.label_4.setMovie(self.pui.movie)
        self.pui.movie.start()


        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ea0004;\">ALICE </span><br/><span style=\" font-size:26pt; color:#ffffff;\">(Artificial Linguistic Internet Computer Entity)</span></p></body></html>"))
import Lucy


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
